### ISSUE TITLE
Receiving a 401 error after a long period, no logs sent to TCP receiver.

### ISSUE THREAD

**Issue by hgoscenski-vail** [duosecurity/duo_log_sync#2]
I am testing this utility, I setup a fluent-bit listening on tcp://localhost:8888 and then enter the appropriate information into the config but after a while I receive this error (full stacktrace below):
```bash
RuntimeError: Received 401 Invalid signature in request credentials
```

I believe this to be a bug in the duo_client, or in this utility, based on these articles: https://help.duo.com/s/article/5444?language=en_US, https://help.duo.com/s/article/1338?language=en_US

Versions:
```bash
[3:00:15] ~/duo_log_sync [master] λ pip3 list | grep duo
duo-client               4.2.3
duologsync               1.0.0
```

Config:
```yaml
[2:13:45] ~/duo_log_sync [master] λ cat config.yml
duoclient:
  skey: "<skey>"
  ikey: "<ikey>"
  host: "<host>"

logs:
  logDir: "/Users/hgoscenski/duo_log_sync/log"
  endpoints:
    enabled: ["auth", "telephony", "adminaction"]
  polling:
    duration: 5
    daysinpast: 60
  checkpointDir: "/Users/hgoscenski/duo_log_sync/log"

transport:
  protocol: "TCP"
  host: "localhost"
  port: 8888
  certFileDir: ""
  certFileName: ""

recoverFromCheckpoint:
  enabled: False
```

Error:
```bash
[1:55:04] ~/duo_log_sync [master] λ duologsync /Users/hgoscenski/duo_log_sync/config.yml
Traceback (most recent call last):
  File "/usr/local/bin/duologsync", line 11, in <module>
    load_entry_point('duologsync==1.0.0', 'console_scripts', 'duologsync')()
  File "/usr/local/lib/python3.7/site-packages/duologsync-1.0.0-py3.7.egg/duologsync/app.py", line 12, in main
  File "/usr/local/lib/python3.7/site-packages/duologsync-1.0.0-py3.7.egg/duologsync/duo_log_sync_base.py", line 79, in start
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/site-packages/duologsync-1.0.0-py3.7.egg/duologsync/producer/authlog_producer.py", line 32, in auth_producer
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/duo_client-4.2.3-py3.7.egg/duo_client/admin.py", line 455, in get_authentication_log
    params,
  File "/usr/local/lib/python3.7/site-packages/duo_client-4.2.3-py3.7.egg/duo_client/client.py", line 383, in json_api_call
    return self.parse_json_response(response, data)
  File "/usr/local/lib/python3.7/site-packages/duo_client-4.2.3-py3.7.egg/duo_client/client.py", line 409, in parse_json_response
    (response, metadata) = self.parse_json_response_and_metadata(response, data)
  File "/usr/local/lib/python3.7/site-packages/duo_client-4.2.3-py3.7.egg/duo_client/client.py", line 438, in parse_json_response_and_metadata
    data['message'],
  File "/usr/local/lib/python3.7/site-packages/duo_client-4.2.3-py3.7.egg/duo_client/client.py", line 422, in raise_error
    raise error
RuntimeError: Received 401 Invalid signature in request credentials
```

**Comment by dcsteve24** [comment]
I had the same error. If I recall correctly, this is tied to not having permissions to read the duo logs. Ensure you are using the "Admin API", not the Auth API like the docs say. To enable the Admin API you have the owner call support and can only enable and see the application from the owner account.

**Comment by hgoscenski-vail** [comment]
Thank you @dcsteve24 for responding. I double checked those settings were configured then after double checking the secret key and integration key, found a typo. It appears to be working now.
