### ISSUE TITLE
Connect call failed ('127.0.0.1', 8888)

### ISSUE THREAD

**Issue by bganeshmail** [duosecurity/duo_log_sync#3]
Team,

We just do fresh install on Ubuntu Linux and setup the DUO log sync .

Ran up with below errors.
ubuntu@ip-172-31-39-49:~/duo_log_sync/duologsync$ duologsync ./config.yml
Exception ignored in: <bound method Task.__del__ of <Task finished coro=<BaseConsumer.get_connection() done, defined at /usr/local/lib/python3.5/dist-packages/duologsync-1.0.0-py3.5.egg/duologsync/consumer/base_consumer.py:15> exception=SystemExit(1,)>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 93, in __del__
  File "/usr/lib/python3.5/asyncio/futures.py", line 215, in __del__
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1177, in call_exception_handler
  File "/usr/lib/python3.5/logging/__init__.py", line 1308, in error
  File "/usr/lib/python3.5/logging/__init__.py", line 1415, in _log
  File "/usr/lib/python3.5/logging/__init__.py", line 1425, in handle
  File "/usr/lib/python3.5/logging/__init__.py", line 1487, in callHandlers
  File "/usr/lib/python3.5/logging/__init__.py", line 855, in handle
  File "/usr/lib/python3.5/logging/__init__.py", line 1047, in emit
  File "/usr/lib/python3.5/logging/__init__.py", line 1037, in _open
NameError: name 'open' is not defined
Exception ignored in: <bound method Task.__del__ of <Task pending coro=<TelephonyProducer.telephony_producer() running at /usr/local/lib/python3.5/dist-packages/duologsync-1.0.0-py3.5.egg/duologsync/producer/telephony_producer.py:24> wait_for=<Future pending cb=[Task._wakeup()]> cb=[gather.<locals>._done_callback(2)() at /usr/lib/python3.5/asyncio/tasks.py:637]>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 92, in __del__
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1177, in call_exception_handler
  File "/usr/lib/python3.5/logging/__init__.py", line 1308, in error
  File "/usr/lib/python3.5/logging/__init__.py", line 1415, in _log
  File "/usr/lib/python3.5/logging/__init__.py", line 1425, in handle
  File "/usr/lib/python3.5/logging/__init__.py", line 1487, in callHandlers
  File "/usr/lib/python3.5/logging/__init__.py", line 855, in handle
  File "/usr/lib/python3.5/logging/__init__.py", line 1047, in emit
  File "/usr/lib/python3.5/logging/__init__.py", line 1037, in _open
NameError: name 'open' is not defined
Exception ignored in: <bound method Task.__del__ of <Task pending coro=<AdminactionProducer.adminaction_producer() running at /usr/local/lib/python3.5/dist-packages/duologsync-1.0.0-py3.5.egg/duologsync/producer/adminaction_producer.py:26> wait_for=<Future pending cb=[Task._wakeup()]> cb=[gather.<locals>._done_callback(4)() at /usr/lib/python3.5/asyncio/tasks.py:637]>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 92, in __del__
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1177, in call_exception_handler
  File "/usr/lib/python3.5/logging/__init__.py", line 1308, in error
  File "/usr/lib/python3.5/logging/__init__.py", line 1415, in _log
  File "/usr/lib/python3.5/logging/__init__.py", line 1425, in handle
  File "/usr/lib/python3.5/logging/__init__.py", line 1487, in callHandlers
  File "/usr/lib/python3.5/logging/__init__.py", line 855, in handle
  File "/usr/lib/python3.5/logging/__init__.py", line 1047, in emit
  File "/usr/lib/python3.5/logging/__init__.py", line 1037, in _open
NameError: name 'open' is not defined
Exception ignored in: <bound method Task.__del__ of <Task pending coro=<AuthlogProducer.auth_producer() running at /usr/local/lib/python3.5/dist-packages/duologsync-1.0.0-py3.5.egg/duologsync/producer/authlog_producer.py:27> wait_for=<Future pending cb=[Task._wakeup()]> cb=[gather.<locals>._done_callback(0)() at /usr/lib/python3.5/asyncio/tasks.py:637]>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 92, in __del__
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1177, in call_exception_handler
  File "/usr/lib/python3.5/logging/__init__.py", line 1308, in error
  File "/usr/lib/python3.5/logging/__init__.py", line 1415, in _log
  File "/usr/lib/python3.5/logging/__init__.py", line 1425, in handle
  File "/usr/lib/python3.5/logging/__init__.py", line 1487, in callHandlers
  File "/usr/lib/python3.5/logging/__init__.py", line 855, in handle
  File "/usr/lib/python3.5/logging/__init__.py", line 1047, in emit
  File "/usr/lib/python3.5/logging/__init__.py", line 1037, in _open
NameError: name 'open' is not defined
Exception ignored in: <bound method Task.__del__ of <Task pending coro=<AdminactionConsumer.consumer() running at /usr/local/lib/python3.5/dist-packages/duologsync-1.0.0-py3.5.egg/duologsync/consumer/adminaction_consumer.py:20> wait_for=<Future pending cb=[Task._wakeup()]> cb=[gather.<locals>._done_callback(5)() at /usr/lib/python3.5/asyncio/tasks.py:637]>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 92, in __del__
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1177, in call_exception_handler
  File "/usr/lib/python3.5/logging/__init__.py", line 1308, in error
  File "/usr/lib/python3.5/logging/__init__.py", line 1415, in _log
  File "/usr/lib/python3.5/logging/__init__.py", line 1425, in handle
  File "/usr/lib/python3.5/logging/__init__.py", line 1487, in callHandlers
  File "/usr/lib/python3.5/logging/__init__.py", line 855, in handle
  File "/usr/lib/python3.5/logging/__init__.py", line 1047, in emit
  File "/usr/lib/python3.5/logging/__init__.py", line 1037, in _open
NameError: name 'open' is not defined
Exception ignored in: <bound method Task.__del__ of <Task pending coro=<TelephonyConsumer.consumer() running at /usr/local/lib/python3.5/dist-packages/duologsync-1.0.0-py3.5.egg/duologsync/consumer/telephony_consumer.py:20> wait_for=<Future pending cb=[Task._wakeup()]> cb=[gather.<locals>._done_callback(3)() at /usr/lib/python3.5/asyncio/tasks.py:637]>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 92, in __del__
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1177, in call_exception_handler
  File "/usr/lib/python3.5/logging/__init__.py", line 1308, in error
  File "/usr/lib/python3.5/logging/__init__.py", line 1415, in _log
  File "/usr/lib/python3.5/logging/__init__.py", line 1425, in handle
  File "/usr/lib/python3.5/logging/__init__.py", line 1487, in callHandlers
  File "/usr/lib/python3.5/logging/__init__.py", line 855, in handle
  File "/usr/lib/python3.5/logging/__init__.py", line 1047, in emit
  File "/usr/lib/python3.5/logging/__init__.py", line 1037, in _open
NameError: name 'open' is not defined
Exception ignored in: <bound method Task.__del__ of <Task pending coro=<AuthlogConsumer.consumer() running at /usr/local/lib/python3.5/dist-packages/duologsync-1.0.0-py3.5.egg/duologsync/consumer/authlog_consumer.py:20> wait_for=<Future pending cb=[Task._wakeup()]> cb=[gather.<locals>._done_callback(1)() at /usr/lib/python3.5/asyncio/tasks.py:637]>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 92, in __del__
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1177, in call_exception_handler
  File "/usr/lib/python3.5/logging/__init__.py", line 1308, in error
  File "/usr/lib/python3.5/logging/__init__.py", line 1415, in _log
  File "/usr/lib/python3.5/logging/__init__.py", line 1425, in handle
  File "/usr/lib/python3.5/logging/__init__.py", line 1487, in callHandlers
  File "/usr/lib/python3.5/logging/__init__.py", line 855, in handle
  File "/usr/lib/python3.5/logging/__init__.py", line 1047, in emit
  File "/usr/lib/python3.5/logging/__init__.py", line 1037, in _open
NameError: name 'open' is not defined
Exception ignored in: <coroutine object AdminactionConsumer.consumer at 0x7f3e974ae468>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/duologsync-1.0.0-py3.5.egg/duologsync/consumer/adminaction_consumer.py", line 20, in consumer
  File "/usr/lib/python3.5/asyncio/queues.py", line 170, in get
  File "/usr/lib/python3.5/asyncio/futures.py", line 227, in cancel
  File "/usr/lib/python3.5/asyncio/futures.py", line 242, in _schedule_callbacks
  File "/usr/lib/python3.5/asyncio/base_events.py", line 497, in call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 506, in _call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 334, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <coroutine object TelephonyConsumer.consumer at 0x7f3e974ae3b8>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/duologsync-1.0.0-py3.5.egg/duologsync/consumer/telephony_consumer.py", line 20, in consumer
  File "/usr/lib/python3.5/asyncio/queues.py", line 170, in get
  File "/usr/lib/python3.5/asyncio/futures.py", line 227, in cancel
  File "/usr/lib/python3.5/asyncio/futures.py", line 242, in _schedule_callbacks
  File "/usr/lib/python3.5/asyncio/base_events.py", line 497, in call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 506, in _call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 334, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <coroutine object AuthlogConsumer.consumer at 0x7f3e974ae308>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/duologsync-1.0.0-py3.5.egg/duologsync/consumer/authlog_consumer.py", line 20, in consumer
  File "/usr/lib/python3.5/asyncio/queues.py", line 170, in get
  File "/usr/lib/python3.5/asyncio/futures.py", line 227, in cancel
  File "/usr/lib/python3.5/asyncio/futures.py", line 242, in _schedule_callbacks
  File "/usr/lib/python3.5/asyncio/base_events.py", line 497, in call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 506, in _call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 334, in _check_closed
RuntimeError: Event loop is closed
ubuntu@ip-172-31-39-49:~/duo_log_sync/duologsync$ pwd
/home/ubuntu/duo_log_sync/duologsync
ubuntu@ip-172-31-39-49:~/duo_log_sync/duologsync$ cd /tmp
ubuntu@ip-172-31-39-49:/tmp$ ls-lrt
ls-lrt: command not found
ubuntu@ip-172-31-39-49:/tmp$ ls -lrt
total 12
drwx------ 3 root   root   4096 Jul  2 09:34 systemd-private-c29b79ac55534ed9a4b6a3030186db9a-systemd-timesyncd.service-NkF2QK
-rw-rw-r-- 1 ubuntu ubuntu 5880 Jul  2 11:28 duologsync.log
ubuntu@ip-172-31-39-49:/tmp$ tail -f duologsync.log
2020-07-02 11:28:52 INFO     Starting duologsync...
2020-07-02 11:28:52 INFO     Configuration loaded successfully...
2020-07-02 11:28:52 INFO     Adminapi initialized for ikey  and host ...
2020-07-02 11:28:52 INFO     Polling duration set is too low. Defaulting to 2mins...
2020-07-02 11:28:52 INFO     Consuming authlogs
2020-07-02 11:28:52 INFO     Consuming telephony log...
2020-07-02 11:28:52 INFO     Consuming adminaction logs...
2020-07-02 11:28:52 INFO     Opening connection to server over tcp...
2020-07-02 11:28:52 ERROR    Connection to server failed with exception [Errno 111] Connect call failed ('127.0.0.1', 8888)
2020-07-02 11:28:52 ERROR    Terminating the application...

**Comment by dcsteve24** [comment]
Do you have anything listening on the server at port 8888?

Do a "nc -zv 127.0.0.1 8888" on the server

**Comment by terrygrace** [comment]
I'm having the same issue using Python 3.6. Nothing listening on tcp/8888. OS is RHEL7
